#!/bin/bash
# script to be executed to run tests on the improved version of the Deck Building Card game.

clear
echo "Hello!"
echo "Compilng code and test files for Deck Building Card Game"
python -m py_compile dbc.py dbcTest.py
echo "Done! Let's start with running the unit tests first for the deck building card game"
python dbcTest.py
echo "==============================================="
echo "Running the actual game for you to play. Enjoy!"
echo "==============================================="
python dbc.py
